lyrics_list =  ['You are the dancing queen\nYoung and sweet\nOnly seventeen',
                'Dancing queen\nFeel the beat from the tambourine, oh yeah',
                'You can dance\nYou can jive','Having the time of your life',
                'Ooh, see that girl\nWatch that scene','Dig in the dancing queen',
                'Knowing me, knowing you (a-ha)\nThere is nothing we can do'
                'Knowing me, knowing you (a-ha)','We just have to face it this time we\'re through'
                'Breaking up is never easy, I know\ nBut I have to go','Knowing me, knowing you',
                'If you change your mind, I\'m the first in line','Honey I\'m still free\nTake a chance on me',
                'If you need me, let me know, gonna be around','If you\'ve got no place to go, if you\'re feeling down',
                'If you\'re all alone when the pretty birds have flown','Honey I\'m still free\nTake a chance on me',
                'Gonna do my very best and it ain\'t no lie','If you put me to the test, if you let me try',
                'Take a chance on me\n(Come on, give me a break will you?)','Take a chance on me',
                'Mamma mia, here I go again','My my, how can I resist you?','Mamma mia, does it show again',
                'My my, just how much I\'ve missed you?','Yes, I\'ve been brokenhearted\nBlue since the day we parted',
                'Why, why did I ever let you go?','Mamma mia, even if I say\n\"Bye bye, leave me now or never\"',
                'Mamma mia, it\'s a game we play\n\"Bye bye\" doesn\'t mean forever','Don\'t go wasting your emotion',
                'Lay all your love on me','Don\'t go sharing your devotion','Lay all your love on me',
                'Tonight the super trouper lights are gonna find me','Shining like the sun (sup-p-per troup-p-per)',
                'Smiling, having fun (sup-p-per troup-p-per)','Feeling like a number one',
                'Tonight the super trouper beams are gonna blind me','But I won\'t feel blue (sup-p-per troup-p-per)',
                'Like I always do (sup-p-per troup-p-per)','Cause somewhere in the crowd there\'s you',
                'I have a dream, a song to sing\nTo help me cope with anything','If you see the wonder of a fairy tale',
                'You can take the future even if you fail','I believe in angels\nSomething good in everything I see',
                'I believe in angels\nWhen I know the time is right for me','I\'ll cross the stream, I have a dream',
                'I don\'t want to talk\nAbout the things we\'ve gone through','Though it\'s hurting me\nNow it\'s history',
                'I\'ve played all my cards\nAnd that\'s what you\'ve done too','Nothing more to say\nNo more ace to play',
                'The winner takes it all','The loser standing small','Beside the victory\nThat\'s her destiny',
                'Money, money, money\nMust be funny','In the rich man\'s world','Money, money, money\nAlways sunny',
                'In the rich man\'s world\nAha aha','All the things I could do','If I had a little money\nIt\'s a rich man\'s world',
                'It\'s a rich man\'s world','So when you\'re near me, darling can\'t you hear me\nS. O. S.',
                'The love you gave me, nothing else can save me\nS. O. S.','When you\'re gone\nHow can I even try to go on?',
                'When you\'re gone\nThough I try how can I carry on?','Chiquitita, you and I know',
                'How the heartaches come and they go and the scars they\'re leaving',
                'You\'ll be dancing once again and the pain will end','You will have no time for grieving',
                'Chiquitita, you and I cry','But the sun is still in the sky and shining above you',
                'Let me hear you sing once more like you did before','Sing a new song, Chiquitita',
                'Try once more like you did before\nSing a new song, Chiquitita','There was something in the air that night',
                'The stars were bright, Fernando','They were shining there for you and me\nFor liberty, Fernando',
                'Though I never thought that we could lose\nThere\'s no regret',
                'If I had to do the same again\I would, my friend, Fernando',
                'If I had to do the same again\nI would, my friend, Fernando','Voulez-vous (ah-ha)\nTake it now or leave it (ah-ha)',
                'Now it\'s all we get (ah-ha)\nNothing promised, no regrets','Voulez-vous (ah-ha)\nAin\'t no big decision (ah-ha)',
                'You know what to do (ah-ha)\nLa question c\'est; voulez-vous','Gimme, gimme, gimme a man after midnight',
                'Won\'t somebody help me\nChase the shadows away','Gimme, gimme, gimme a man after midnight',
                'Take me through the darkness\nTo the break of the day','Gimme, gimme, gimme a man after midnight',
                'Gimme, gimme, gimme a man after midnight','There\'s not a soul out there\nNo one to hear my prayer',
                'Well I can dance with you honey\nIf you think it\'s funny','Does your mother know that you\'re out',
                'And I can chat with you baby\nFlirt a little maybe','Does your mother know that you\'re out',
                'Take it easy (take it easy)\nBetter slow down girl','That\'s no way to go\nDoes your mother know',
                'Take it easy (take it easy)\nTry to cool it girl','Take it nice and slow\nDoes your mother know',
                'One of us is crying','One of us is lying\nIn her lonely bed',
                'Staring at the ceiling\nWishing she was somewhere else instead','One of us is lonely',
                'One of us is only\nWaiting for a call','Sorry for herself, feeling stupid feeling small',
                'Wishing she had never left at all','What\'s the name of the game?\nDoes it mean anything to you?',
                'What\'s the name of the game?\nCan you feel it the way I do?','Tell me please, \'cause I have to know',
                'I\'m a bashful child, beginning to grow','And you make me talk\And you make me feel',
                'And you make me show\nWhat I\'m trying to conceal','If I trust in you, would you let me down?',
                'Would you laugh at me, if I said I care for you?','Could you feel the same way too?',
                'I wanna know\nOh yes I wanna know','So I say\nThank you for the music, the songs I\'m singing',
                'Thanks for all the joy they\'re bringing','Who can live without it, I ask in all honesty',
                'What would life be?\nWithout a song or a dance what are we?',
                'So I say thank you for the music\nFor giving it to me','Oh, oh Waterloo finally facing my Waterloo',
                'So how could I ever refuse\nI feel like I win when I lose','Waterloo couldn\'t escape if I wanted to',
                'Waterloo knowing my fate is to be with you','Waterloo finally facing my Waterloo',
                'Waterloo knowing my fate is to be with you','Oh, oh Waterloo finally facing my Waterloo',
                'Waterloo knowing my fate is to be with you','Waterloo I was defeated, you won the war',
                'Waterloo promise to love you for ever more']